from .design_prompts import SVG_LOGO_SYSTEM_PROMPT
from .marketing_prompts import BLOG_DRAFT_SYSTEM_PROMPT, REJECTION_REASON_PROMPT
from .patrol_prompts import (
    API_DEPRECATION_SCAN_PROMPT,
    CHARLIE_ASSISTANT_PM,
    CODE_EXAMPES_AUDITOR,
    LEADS_PATROL_PROMPT,
    PROJECT_OWNER_ASSISTANT_PO,
    SOURCE_METADATA_SUMMARY,
    SOURCE_TITLE_GENERATOR,
    SYS_ERROR_PATROL_PROMPT,
    TECH_DEBT_CLEANUP_PROMPT,
    TECH_DEBT_SSOT_AUDIT_PROMPT,
)
from .pm_prompts import (
    DAILY_EXECUTIVE_SUMMARY_DEFAULT,
    ENGINEERING_RETRO_DEFAULT,
    MONTHLY_EXECUTIVE_SUMMARY_DEFAULT,
    REPORT_CONTEXT_DEFAULT,
    REPORT_CONTEXT_FALLBACK,
    USER_STORY_SYSTEM_PROMPT,
    WEEKLY_EXECUTIVE_SUMMARY_DEFAULT,
)
from .rag_prompts import (
    DATA_EXTRACTION_EXPERT_PROMPT,
    DATA_EXTRACTION_PROMPT_DEFAULT,
    EMBED_CONTEXT_GENERATOR_PROMPT,
    LIBRARIAN_SYSTEM_PROMPT,
)
from .sales_prompts import (
    ALICE_HYDE_BASELINE_DEFAULT,
    ALICE_INFER_NEED_DEFAULT,
    ALICE_LEAD_JUDGE_DEFAULT,
    SALES_PITCH_SYSTEM_PROMPT,
)

ALL_PROMPTS = {
    "SVG_LOGO_SYSTEM": SVG_LOGO_SYSTEM_PROMPT,
    "BLOG_DRAFT": BLOG_DRAFT_SYSTEM_PROMPT,
    "REJECT_SUGGESTION": REJECTION_REASON_PROMPT,
    "USER_STORY_SYSTEM": USER_STORY_SYSTEM_PROMPT,
    "REPORT_CONTEXT_PROMPT": REPORT_CONTEXT_DEFAULT,
    "REPORT_CONTEXT_FALLBACK": REPORT_CONTEXT_FALLBACK,
    "DAILY_EXECUTIVE_SUMMARY_PROMPT": DAILY_EXECUTIVE_SUMMARY_DEFAULT,
    "WEEKLY_EXECUTIVE_SUMMARY": WEEKLY_EXECUTIVE_SUMMARY_DEFAULT,
    "MONTHLY_EXECUTIVE_SUMMARY": MONTHLY_EXECUTIVE_SUMMARY_DEFAULT,
    "ENGINEERING_RETRO_DEFAULT": ENGINEERING_RETRO_DEFAULT,
    "LIBRARIAN_SYSTEM": LIBRARIAN_SYSTEM_PROMPT,
    "EMBED_CONTEXT_GENERATOR": EMBED_CONTEXT_GENERATOR_PROMPT,
    "data_extraction_prompt": DATA_EXTRACTION_PROMPT_DEFAULT,
    "DATA_EXTRACTION_EXPERT": DATA_EXTRACTION_EXPERT_PROMPT,
    "SALES_PITCH": SALES_PITCH_SYSTEM_PROMPT,
    "ALICE_HYDE_BASELINE": ALICE_HYDE_BASELINE_DEFAULT,
    "ALICE_LEAD_JUDGE": ALICE_LEAD_JUDGE_DEFAULT,
    "ALICE_INFER_NEED": ALICE_INFER_NEED_DEFAULT,
    "SYS_ERROR_PATROL_PROMPT": SYS_ERROR_PATROL_PROMPT,
    "LEADS_PATROL_PROMPT": LEADS_PATROL_PROMPT,
    "API_DEPRECATION_SCAN_PROMPT": API_DEPRECATION_SCAN_PROMPT,
    "TECH_DEBT_CLEANUP_PROMPT": TECH_DEBT_CLEANUP_PROMPT,
    "TECH_DEBT_SSOT_AUDIT_PROMPT": TECH_DEBT_SSOT_AUDIT_PROMPT,
    "SOURCE_METADATA_SUMMARY": SOURCE_METADATA_SUMMARY,
    "SOURCE_TITLE_GENERATOR": SOURCE_TITLE_GENERATOR,
    "CODE_EXAMPES_AUDITOR": CODE_EXAMPES_AUDITOR,
    "PROJECT_OWNER_ASSISTANT_PO": PROJECT_OWNER_ASSISTANT_PO,
    "CHARLIE_ASSISTANT_PM": CHARLIE_ASSISTANT_PM,
}
