-- Migration: 006_create_sales_intel_tables.sql
-- Description: Creates tables for Sales Intelligence (Leads and Market Insights)
-- Date: 2026-01-05

-- 1. 潛在客戶表 (Leads Table)
-- Stores companies identified via job market search that have potential needs.
CREATE TABLE IF NOT EXISTS leads (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_name TEXT NOT NULL,          -- 公司名稱
    source_job_url TEXT,                 -- 來源職缺連結
    status TEXT DEFAULT 'new',           -- 狀態: new, contacted, qualified, converted
    identified_need TEXT,                -- 識別出的需求 (e.g. "Needs BI Tool")
    assigned_sales_id UUID REFERENCES auth.users(id), -- 分配給哪位業務
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 市場洞察表 (Market Insights Table)
-- Stores aggregated data or specific analysis results generated by Agents.
CREATE TABLE IF NOT EXISTS market_insights (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    keyword TEXT NOT NULL,               -- 搜尋關鍵字 (e.g. "Business Analyst")
    insight_summary TEXT,                -- AI 生成的市場分析摘要
    related_blog_id UUID REFERENCES blog_posts(id), -- 建議搭配的部落格文章
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Add updated_at trigger for leads
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_leads_updated_at
    BEFORE UPDATE ON leads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Enable Row Level Security (RLS)
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE market_insights ENABLE ROW LEVEL SECURITY;

-- Simple policies (Can be refined later based on RBAC requirements)
-- Allow authenticated users to select records
CREATE POLICY "Allow authenticated users to view leads" ON leads
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated users to view insights" ON market_insights
    FOR SELECT USING (auth.role() = 'authenticated');
