import { callAPIWithETag } from '@/features/shared/api/apiClient';

export interface BugContext {
  error: { message: string; stack?: string; name: string; };
  app: { version: string; url: string; timestamp: string; };
  system: { platform: string; userAgent: string; memory?: string; };
  services: { server: boolean; mcp: boolean; agents: boolean; };
  logs: string[];
}

export interface BugReportData {
  title: string;
  description: string;
  stepsToReproduce: string;
  expectedBehavior: string;
  actualBehavior: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  component: string;
  context: BugContext;
}

class BugReportService {
  async collectBugContext(error?: Error): Promise<BugContext> {
    return {
      error: { message: error?.message || 'Manual bug report', stack: error?.stack, name: error?.name || 'UserReportedError' },
      app: { version: await this.getVersion(), url: window.location.href, timestamp: new Date().toISOString() },
      system: { platform: navigator.platform, userAgent: navigator.userAgent, memory: 'unknown' },
      services: await this.quickHealthCheck(),
      logs: []
    };
  }

  private async getVersion(): Promise<string> {
    try {
      const data = await callAPIWithETag<any>('/version/current');
      return data.version || 'v0.2.0';
    } catch {
      return 'v0.2.0';
    }
  }

  private async quickHealthCheck(): Promise<{ server: boolean; mcp: boolean; agents: boolean; }> {
    const services = { server: false, mcp: false, agents: false };
    try {
      const checks = await Promise.allSettled([
        callAPIWithETag('/health'),
        callAPIWithETag('/mcp/health'),
        callAPIWithETag('/agents/health')
      ]);
      services.server = checks[0].status === 'fulfilled';
      services.mcp = checks[1].status === 'fulfilled';
      services.agents = checks[2].status === 'fulfilled';
    } catch (e) {
      console.warn('Quick health check failed:', e);
    }
    return services;
  }

  async submitBugReport(bugReport: BugReportData): Promise<any> {
    try {
      const result = await callAPIWithETag<any>('/bug-report/github', {
        method: 'POST',
        body: JSON.stringify(bugReport)
      });
      return { success: result.success, issueUrl: result.issue_url };
    } catch (e: any) {
      return { success: false, error: e.message };
    }
  }

  formatReportForClipboard(bugReport: BugReportData): string {
    return `
# 🐛 Bug Report
**Version:** ${bugReport.context.app.version}
**Severity:** ${bugReport.severity}
**Description:** ${bugReport.description}
**Error:** ${bugReport.context.error.message}
---
*Generated by Archon Bug Reporter*
    `.trim();
  }
}

export const bugReportService = new BugReportService();
