import React, { useState, useEffect } from 'react';

interface BrandLogoProps {
    className?: string;
    showText?: boolean;
}

export const BrandLogo: React.FC<BrandLogoProps> = ({ className = "w-8 h-8", showText = true }) => {
    const [svgContent, setSvgContent] = useState<string | null>(null);
    const [error, setError] = useState(false);

    useEffect(() => {
        let isMounted = true;
        // Try to fetch the dynamic asset generated by DevBot
        fetch('/logo-eciton.svg')
            .then(res => {
                if (!res.ok) throw new Error("Asset not found");
                return res.text();
            })
            .then(text => {
                if (!isMounted) return;
                // Basic validation to ensure it's an SVG
                if (text.trim().startsWith('<svg')) {
                    setSvgContent(text);
                } else {
                    throw new Error("Invalid SVG content");
                }
            })
            .catch(() => {
                if (isMounted) setError(true);
            });
        
        return () => {
            isMounted = false;
        };
    }, []);

    // Fallback: Text Logo (Before DevBot runs)
    if (error || !svgContent) {
        return (
            <div className={`flex items-center gap-2 ${className}`}>
                <div className="w-full h-full rounded-full bg-gradient-to-br from-cyan-400 to-purple-600 flex items-center justify-center text-white font-bold text-xs shadow-lg animate-pulse">
                    M
                </div>
                {showText && <span className="font-bold text-xl tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-cyan-500 to-purple-600">Myrmidon</span>}
            </div>
        );
    }

    // Success: Render the generated SVG
    // Using dangerouslySetInnerHTML is safe here because the source is our own backend
    return (
        <div className={`flex items-center gap-2`}>
            <div 
                className={`${className} [&>svg]:w-full [&>svg]:h-full`}
                dangerouslySetInnerHTML={{ __html: svgContent }} 
            />
            {showText && <span className="font-bold text-xl tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-cyan-500 to-purple-600">Myrmidon</span>}
        </div>
    );
};
