import { authApi } from './auth';
import { tasksApi } from './tasks';
import { statsApi } from './stats';
import { opsApi } from './ops';

/**
 * Modularized API Service for Archon End-User UI.
 * Achieves L2 Hardening by domain separation.
 * 
 * Hardened version for Phase 4.6.59+
 */
export const api = {
  // Auth
  login: authApi.login.bind(authApi),
  register: authApi.register.bind(authApi),
  logout: authApi.logout.bind(authApi),
  getCurrentUser: authApi.getCurrentUser.bind(authApi),
  getSystemPermissions: authApi.getSystemPermissions.bind(authApi),
  updateUserEmail: authApi.updateUserEmail.bind(authApi),
  updateUserPassword: authApi.updateUserPassword.bind(authApi),
  updateEmployee: authApi.updateEmployee.bind(authApi),
  getEmployees: authApi.getEmployees.bind(authApi),
  adminCreateUser: authApi.adminCreateUser.bind(authApi),
  getAssignableUsers: authApi.getAssignableUsers.bind(authApi),
  getAssignableAgents: authApi.getAssignableAgents.bind(authApi),
  resetPassword: authApi.resetPassword.bind(authApi),
  getRBACMatrix: authApi.getRBACMatrix.bind(authApi),
  updateRBACRole: authApi.updateRBACRole.bind(authApi),

  // Tasks
  getTasks: tasksApi.getTasks.bind(tasksApi),
  deleteTask: tasksApi.deleteTask.bind(tasksApi),
  getProjects: tasksApi.getProjects.bind(tasksApi),
  createProject: tasksApi.createProject.bind(tasksApi),
  createTask: tasksApi.createTask.bind(tasksApi),
  updateTask: tasksApi.updateTask.bind(tasksApi),
  refineTaskDescription: tasksApi.refineTaskDescription.bind(tasksApi),
  generateTaskFromAlert: tasksApi.generateTaskFromAlert.bind(tasksApi),
  getPendingChanges: tasksApi.getPendingChanges.bind(tasksApi),
  approveChange: tasksApi.approveChange.bind(tasksApi),
  rejectChange: tasksApi.rejectChange.bind(tasksApi),
  approvePromptChange: tasksApi.approvePromptChange.bind(tasksApi),

  // Stats
  getAgentXPStats: statsApi.getAgentXPStats.bind(statsApi),
  getTaskDistribution: statsApi.getTaskDistribution.bind(statsApi),
  getAiUsage: statsApi.getAiUsage.bind(statsApi),
  getSystemOverview: statsApi.getSystemOverview.bind(statsApi),
  getMemberPerformance: statsApi.getMemberPerformance.bind(statsApi),
  getTokenUsageDetails: statsApi.getTokenUsageDetails.bind(statsApi),
  getRecentTokenUsage: statsApi.getRecentTokenUsage.bind(statsApi),
  getHealthTrend: statsApi.getHealthTrend.bind(statsApi),
  getCommanderTrends: statsApi.getCommanderTrends.bind(statsApi),
  getForceReadiness: statsApi.getForceReadiness.bind(statsApi),
  getCollabSynergy: statsApi.getCollabSynergy.bind(statsApi),
  getSlaReliability: statsApi.getSlaReliability.bind(statsApi),
  getEthicsAuditQueue: statsApi.getEthicsAuditQueue.bind(statsApi),
  getKnowledgeRoi: statsApi.getKnowledgeRoi.bind(statsApi),
  getBusinessRisks: statsApi.getBusinessRisks.bind(statsApi),
  getPendingApprovals: statsApi.getPendingApprovals.bind(statsApi),
  processApproval: statsApi.processApproval.bind(statsApi),
  generateRejectReason: statsApi.generateRejectReason.bind(statsApi),
  getMarketingTrends: statsApi.getMarketingTrends.bind(statsApi),
  getMarketStats: statsApi.getMarketStats.bind(statsApi),
  getMarketingIntelligence: statsApi.getMarketingIntelligence.bind(statsApi),
  rejectSuggestion: statsApi.rejectSuggestion.bind(statsApi),
  nanaBananaProxy: statsApi.nanaBananaProxy.bind(statsApi),

  // Ops
  searchJobs: opsApi.searchJobs.bind(opsApi),
  generatePitch: opsApi.generatePitch.bind(opsApi),
  getSystemPrompts: opsApi.getSystemPrompts.bind(opsApi),
  updateSystemPrompt: opsApi.updateSystemPrompt.bind(opsApi),
  getSystemSettings: opsApi.getSystemSettings.bind(opsApi),
  updateSystemSetting: opsApi.updateSystemSetting.bind(opsApi),
  analyzeExtractionUrl: opsApi.analyzeExtractionUrl.bind(opsApi),
  getExtractionSchemas: opsApi.getExtractionSchemas.bind(opsApi),
  createExtractionSchema: opsApi.createExtractionSchema.bind(opsApi),
  deleteExtractionSchema: opsApi.deleteExtractionSchema.bind(opsApi),
  runExtraction: opsApi.runExtraction.bind(opsApi),
  getAiHealth: opsApi.getAiHealth.bind(opsApi),
  getManagerAlerts: opsApi.getManagerAlerts.bind(opsApi),
  getAlerts: opsApi.getAlerts.bind(opsApi),
  dispatchAlertTask: opsApi.dispatchAlertTask.bind(opsApi),
  seedKnowledgeBase: opsApi.seedKnowledgeBase.bind(opsApi),
  getVisitLogs: opsApi.getVisitLogs.bind(opsApi),
  createVisitLog: opsApi.createVisitLog.bind(opsApi),
  getAttendanceStatus: opsApi.getAttendanceStatus.bind(opsApi),
  clockIn: opsApi.clockIn.bind(opsApi),
  clockOut: opsApi.clockOut.bind(opsApi),
  getEthicsEvents: opsApi.getEthicsEvents.bind(opsApi),
  triggerSentinel: opsApi.triggerSentinel.bind(opsApi),
  getLeads: opsApi.getLeads.bind(opsApi),
  createLead: opsApi.createLead.bind(opsApi),
  updateLead: opsApi.updateLead.bind(opsApi),
  promoteLead: opsApi.promoteLead.bind(opsApi),
  resetLeads: opsApi.resetLeads.bind(opsApi),
  getBlogPosts: opsApi.getBlogPosts.bind(opsApi),
  getBlogPost: opsApi.getBlogPost.bind(opsApi),
  createBlogPost: opsApi.createBlogPost.bind(opsApi),
  updateBlogPost: opsApi.updateBlogPost.bind(opsApi),
  deleteBlogPost: opsApi.deleteBlogPost.bind(opsApi),
  draftBlogPost: opsApi.draftBlogPost.bind(opsApi),
  draftFromLeads: opsApi.draftFromLeads.bind(opsApi),
  submitBlogPost: opsApi.submitBlogPost.bind(opsApi),
  updateBlogPostStatus: opsApi.updateBlogPostStatus.bind(opsApi),
  uploadFile: opsApi.uploadFile.bind(opsApi),
  getKnowledgeItems: opsApi.getKnowledgeItems.bind(opsApi),
  searchKnowledgeItems: opsApi.searchKnowledgeItems.bind(opsApi),
  getCrawlerTargets: opsApi.getCrawlerTargets.bind(opsApi),
  createCrawlerTarget: opsApi.createCrawlerTarget.bind(opsApi),
  deleteCrawlerTarget: opsApi.deleteCrawlerTarget.bind(opsApi),
  getDocumentVersions: opsApi.getDocumentVersions.bind(opsApi),
  getConnectivityLogs: opsApi.getConnectivityLogs.bind(opsApi),
  getConnectivityLogsByType: opsApi.getConnectivityLogsByType.bind(opsApi),
  getContentSources: opsApi.getContentSources.bind(opsApi),
  getContentContext: opsApi.getContentContext.bind(opsApi),
  generateLogo: opsApi.generateLogo.bind(opsApi),
  diagnoseFile: opsApi.diagnoseFile.bind(opsApi),
};

export { supabase } from './client';
export * from './types';
