export const ROUTES = {
  LANDING: '/landing',
  BLOG: '/blog',
  BLOG_DETAIL: '/blog/:id',
  SOLUTIONS: '/solutions',
  AUTH: '/auth',
  GAME_CARD_BATTLER: '/game/card-battler',
  DASHBOARD: '/dashboard',
  STATS: '/stats',
  MARKETING: '/marketing',
  BRAND: '/brand',
  SALES_CART: '/sales-cart',
  TEAM: '/team',
  APPROVALS: '/approvals',
  ADMIN: '/admin',
  BRAND_EDITOR: '/brand/editor/:id',
  NEXUS: '/nexus',
  SETTINGS: '/settings',
};
