import { test, expect } from '@playwright/test';
import { waitForSpinner } from './fixtures/systemFixtures';

// Setup Manager Auth State
test.use({ storageState: '../.playwright/admin_storage_state.json' });

test.describe('Daily Executive Summary (Phase 5.1.11 Fan-out)', () => {

  test('should physically render [Daily Report] Executive Summary card in UI', async ({ page }) => {
    page.on('console', msg => console.log('PAGE LOG:', msg.text()));
    page.on('requestfailed', request => console.log('REQ FAILED:', request.url(), request.failure()?.errorText));

    // 1. Intercept the required APIs for DashboardPage
    await page.route(/\/api\/projects($|\?)/, async route => { 
        await route.fulfill({ status: 200, json: [] }); 
    });
    await page.route(/\/api\/admin\/users($|\?)/, async route => { 
        await route.fulfill({ status: 200, json: [] }); 
    });
    await page.route(/\/api\/changes($|\?)/, async route => { await route.fulfill({ status: 200, json: [] }); });
    await page.route(/\/api\/stats\/.*/, async route => { await route.fulfill({ status: 200, json: [] }); });
    await page.route(/\/api\/logs\/.*/, async route => { await route.fulfill({ status: 200, json: [] }); });
    await page.route(/\/api\/system\/settings($|\?)/, async route => { await route.fulfill({ status: 200, json: [] }); });
    await page.route(/\/api\/marketing\/approvals($|\?)/, async route => { await route.fulfill({ status: 200, json: {blogs:[]} }); });

    await page.route(/\/api\/tasks($|\?)/, async route => {
      await route.fulfill({
        status: 200,
        contentType: 'application/json',
        body: JSON.stringify([
          {
            id: "task-daily-report-mock",
            project_id: "mock-project-id",
            title: "[Daily Report] Executive Summary",
            description: "This is a mock daily report generated by the Fan-out Engine.\n\n- Sales: 10 leads\n- Marketing: 5 campaigns\n- System: All green",
            status: "done",
            priority: "high",
            agent_output: {
               content: "Final Map-Reduce Summary Here."
            },
            assignee_id: "charlie-manager-uuid",
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
          }
        ])
      });
    });

    // 2. Navigate to the Tasks Dashboard
    await page.goto('/#/dashboard');
    
    // 3. Wait for loading to finish
    await waitForSpinner(page);

    // 4. Physical Assertion: The card MUST exist in the DOM
    const dailyReportCard = page.locator('text="[Daily Report] Executive Summary"');
    await expect(dailyReportCard).toBeVisible({ timeout: 10000 });

    // 5. Click to expand TaskModal
    await dailyReportCard.click();
    
    // 6. Navigate to AI Report tab and verify contents
    const aiReportTab = page.locator('text="AI Report"');
    await aiReportTab.click();
    
    await expect(page.getByText("Final Map-Reduce Summary Here.").first()).toBeVisible({ timeout: 10000 });
  });

});